# Generated by Django 5.0.6 on 2024-06-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_account",
            "0002_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="confirm_password",
        ),
    ]
